server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: postgres
    password: 1234
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/banking
management:
  endpoints:
    web:
      exposure:
        include: "*"
keycloak:
  server-url: http://localhost:8180
  realm: banking
  admin:
    realm: master
    username: admin
    password: admin
    client-id: admin-cli
