server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: 1234
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/banking
management:
  endpoints:
    web:
      exposure:
        include: "*"
