server:
  port: 8084
spring:
  application:
    name: simulator-service
  datasource:
    url: jdbc:postgresql://localhost:5432/simulator
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    import: "configserver:http://localhost:8888,vault://"
  cloud:
    config:
      label: main
    vault:
      uri: http://localhost:8200
      token: root
      kv:
        enabled: true
        backend: secret
        default-context: banking
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      auto-create: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/banking
simulator:
  min-amount: 10
  max-amount: 10000
management:
  endpoints:
    web:
      exposure:
        include: "*"
